### ISSUE TITLE
Reduce the expression graph

### ISSUE THREAD

**Issue by charlesm93** [metrumresearchgroup/math#2] opened 2017-07-31 13:39 UTC
#### Summary:
Stan computes the gradient of the log posterior by applying the chain rule. The code can gain in efficiency if we reduce the expression graph, thereby decreasing the number of times Stan applies the chain rule.

#### Description:
If an expression, say k^2, appears multiple times, it pays off to create a k_square variable.

#### Reproducible Steps:
I'm actually not sure how big the gain in computational efficiency will be, but I am basing this on feedback I got from Bob when working on the matrix exponential: https://github.com/stan-dev/math/pull/390#event-861637530

I'll compare the number of effective samples per unit time between old and new versions of Torsten.

#### Current Output:
Code works fine but there may be a way to speed it up.

#### Expected Output:
Expect a speed up.

#### Current Version:
Stan v2.12.0
Torsten v0.81

**Comment by yizhang-yiz** [comment] 2019-02-26 23:47
I'm closing it since the issue is unspecific.

**Closed as completed by yizhang-yiz** 2019-02-26 23:47 UTC
